onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /control_unit_tb/DUT/ir_data
add wave -noupdate /control_unit_tb/reset
add wave -noupdate /control_unit_tb/clk
add wave -noupdate /control_unit_tb/DUT/reset
add wave -noupdate /control_unit_tb/DUT/clr
add wave -noupdate /control_unit_tb/DUT/ir_clr
add wave -noupdate /control_unit_tb/DUT/y_clr
add wave -noupdate /control_unit_tb/DUT/bus
add wave -noupdate /control_unit_tb/DUT/mdr_connection
add wave -noupdate /control_unit_tb/DUT/alu_out
add wave -noupdate /control_unit_tb/DUT/op_code
add wave -noupdate /control_unit_tb/DUT/m_data_in
add wave -noupdate /control_unit_tb/DUT/con_out
add wave -noupdate /control_unit_tb/DUT/ram_write
add wave -noupdate /control_unit_tb/DUT/r0_enable
add wave -noupdate /control_unit_tb/DUT/r1_enable
add wave -noupdate /control_unit_tb/DUT/r2_enable
add wave -noupdate /control_unit_tb/DUT/r3_enable
add wave -noupdate /control_unit_tb/DUT/r4_enable
add wave -noupdate /control_unit_tb/DUT/r5_enable
add wave -noupdate /control_unit_tb/DUT/r6_enable
add wave -noupdate /control_unit_tb/DUT/r7_enable
add wave -noupdate /control_unit_tb/DUT/r8_enable
add wave -noupdate /control_unit_tb/DUT/r8_enable_select
add wave -noupdate /control_unit_tb/DUT/r8_in
add wave -noupdate /control_unit_tb/DUT/r9_enable
add wave -noupdate /control_unit_tb/DUT/r10_enable
add wave -noupdate /control_unit_tb/DUT/r11_enable
add wave -noupdate /control_unit_tb/DUT/r12_enable
add wave -noupdate /control_unit_tb/DUT/r13_enable
add wave -noupdate /control_unit_tb/DUT/r14_enable
add wave -noupdate /control_unit_tb/DUT/r15_enable
add wave -noupdate /control_unit_tb/DUT/y_enable
add wave -noupdate /control_unit_tb/DUT/hi_enable
add wave -noupdate /control_unit_tb/DUT/lo_enable
add wave -noupdate /control_unit_tb/DUT/z_enable
add wave -noupdate /control_unit_tb/DUT/pc_enable
add wave -noupdate /control_unit_tb/DUT/mar_enable
add wave -noupdate /control_unit_tb/DUT/mdr_enable
add wave -noupdate /control_unit_tb/DUT/ir_enable
add wave -noupdate /control_unit_tb/DUT/r0_out
add wave -noupdate /control_unit_tb/DUT/r1_out
add wave -noupdate /control_unit_tb/DUT/r2_out
add wave -noupdate /control_unit_tb/DUT/r3_out
add wave -noupdate /control_unit_tb/DUT/r4_out
add wave -noupdate /control_unit_tb/DUT/r5_out
add wave -noupdate /control_unit_tb/DUT/r6_out
add wave -noupdate /control_unit_tb/DUT/r7_out
add wave -noupdate /control_unit_tb/DUT/r8_out
add wave -noupdate /control_unit_tb/DUT/r9_out
add wave -noupdate /control_unit_tb/DUT/r10_out
add wave -noupdate /control_unit_tb/DUT/r11_out
add wave -noupdate /control_unit_tb/DUT/r12_out
add wave -noupdate /control_unit_tb/DUT/r13_out
add wave -noupdate /control_unit_tb/DUT/r14_out
add wave -noupdate /control_unit_tb/DUT/r15_out
add wave -noupdate /control_unit_tb/DUT/pc_out
add wave -noupdate /control_unit_tb/DUT/hi_out
add wave -noupdate /control_unit_tb/DUT/lo_out
add wave -noupdate /control_unit_tb/DUT/zhi_out
add wave -noupdate /control_unit_tb/DUT/zlo_out
add wave -noupdate /control_unit_tb/DUT/mdr_out
add wave -noupdate /control_unit_tb/DUT/inport_out
add wave -noupdate /control_unit_tb/DUT/c_sign_extended_out
add wave -noupdate /control_unit_tb/DUT/ba_out
add wave -noupdate /control_unit_tb/DUT/gra
add wave -noupdate /control_unit_tb/DUT/grb
add wave -noupdate /control_unit_tb/DUT/grc
add wave -noupdate /control_unit_tb/DUT/r_out
add wave -noupdate /control_unit_tb/DUT/r0_data
add wave -noupdate /control_unit_tb/DUT/r0_content
add wave -noupdate /control_unit_tb/DUT/r1_data
add wave -noupdate /control_unit_tb/DUT/r2_data
add wave -noupdate /control_unit_tb/DUT/r3_data
add wave -noupdate /control_unit_tb/DUT/r4_data
add wave -noupdate /control_unit_tb/DUT/r5_data
add wave -noupdate /control_unit_tb/DUT/r6_data
add wave -noupdate /control_unit_tb/DUT/r7_data
add wave -noupdate /control_unit_tb/DUT/r8_data
add wave -noupdate /control_unit_tb/DUT/r9_data
add wave -noupdate /control_unit_tb/DUT/r10_data
add wave -noupdate /control_unit_tb/DUT/r11_data
add wave -noupdate /control_unit_tb/DUT/r12_data
add wave -noupdate /control_unit_tb/DUT/r13_data
add wave -noupdate /control_unit_tb/DUT/r14_data
add wave -noupdate /control_unit_tb/DUT/r15_data
add wave -noupdate /control_unit_tb/DUT/y_data
add wave -noupdate /control_unit_tb/DUT/pc_data
add wave -noupdate /control_unit_tb/DUT/pc_incremented
add wave -noupdate /control_unit_tb/DUT/c_data
add wave -noupdate /control_unit_tb/DUT/hi_data
add wave -noupdate /control_unit_tb/DUT/lo_data
add wave -noupdate /control_unit_tb/DUT/zhi_data
add wave -noupdate /control_unit_tb/DUT/mdr_data
add wave -noupdate /control_unit_tb/DUT/mar_data
add wave -noupdate /control_unit_tb/DUT/zlo_data
add wave -noupdate /control_unit_tb/DUT/z_input
add wave -noupdate /control_unit_tb/DUT/pc_increment
add wave -noupdate /control_unit_tb/DUT/r_in
add wave -noupdate /control_unit_tb/DUT/read
add wave -noupdate /control_unit_tb/DUT/con_enable
add wave -noupdate /control_unit_tb/DUT/outport_enable
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6111791 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 231
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {6106280 ps} {7524732 ps}
